//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTabadol.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo_Table
    {
        public long ChatId { get; set; }
        public Nullable<long> ChannelId { get; set; }
        public Nullable<long> BannerPath { get; set; }
        public string Category1 { get; set; }
        public string Category2 { get; set; }
        public string Category3 { get; set; }
        public Nullable<int> DayliTab { get; set; }
        public Nullable<long> MemberCount { get; set; }
        public Nullable<bool> Recive { get; set; }
        public Nullable<int> LastTabTimeToDay { get; set; }
    }
}
